### ISSUE TITLE
Update MiDAS functions to the newest version

### ISSUE THREAD

**Issue by MadsAlbertsen** [MadsAlbertsen/ampvis#19]
The MiDAS functions are behind the version available online.

**Comment by Kirk3gaard** [comment]
We could potentially integrate a solution that reads it directly from the SQL table?

https://www.dropbox.com/s/qsxfknaz8tj488m/20151105_MiF.RData?dl=0

**Comment by MadsAlbertsen** [comment]
I've updated to the newest version and also made a small wrapper script for future updates. 

Yep - direct integration with the SQL table would make it more easy in the future.
