### ISSUE TITLE
Transformation introduced infinite values in discrete y-axis 

### ISSUE THREAD

**Issue by bstamps** [MadsAlbertsen/ampvis#33]
Hello, 

I'm trying to work through an 18S rRNA gene dataset, and visualize using Phyloseq/AmpVis. My dataset loads into a Phyloseq object seemingly OK, but attempting to plot a heatmap in any meaningful way always results in some issues. As the subject line says, any time I try to plot I receive this error: 

```
> amp_heatmap(data = dsn, 
+             group = c("Tank", "ExposureTime"), 
+             tax.class = "D_3__Fungi",
+             scale.seq = 100)
Warning message:
Transformation introduced infinite values in discrete y-axis 

```

Any ideas on what could be causing it? Prior to running the above script I renamed the taxonomic levels as suggested on the PhyloSeq page as below- 

`colnames(tax_table(dsn)) = c("Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Species")`

Thank you for any help!

**Comment by KasperSkytte** [comment]
Warnings should just be ignored. Your analysis will be fine :)
